<?php


function rating_hubs_taxonomy_term_view($term, $view_mode = 'full')
{
  if ($view_mode == 'full') {

    $record = rating_hubs_get_record($term->tid);

    if ($record === FALSE) {
      $record = new StdClass();
      $record->tid = $term->tid;
      $record->term_name = $term->name;
    }
    rating_hubs_set_record($record);

    $query = db_select('rating_hubs', 'r');
    $query->join('taxonomy_term_data', 't', 't.tid = r.tid');
    $query->fields('t', array('name','tid'))
        ->condition('t.tid', 'r.tid', '=');
    $result = $query->execute();

    }
  }



function rating_hubs_get_record($tid)
{
  $query = db_select('rating_hubs', 'r')
      ->fields('r', array('tid','term_name'))
      ->condition('tid', $tid);
  $record = $query->execute()->fetch();
  return $record;
}


function rating_hubs_set_record($record)
{

  $query = db_insert('rating_hubs')
      ->fields((array)$record);
  $query->execute();
}





