<?php

function node_stat_node_view($node, $view_mode = 'full') {
  if ($view_mode == 'full') {

    global $user;

    $record = node_stat_get_record($node->nid, $user->uid);

    if ($record === FALSE) {
      $record = new StdClass();
      $record->nid = $node->nid;
      $record->uid = $user->uid;
      $record->last_viewed = time();
    }

    $record->last_viewed = time();

    node_stat_set_record($record);

    $total = db_select('node_stat', 'd')
      ->fields('d')
      ->condition('nid', $node->nid)
      ->execute();
    $num_of_total = $total->rowCount();

    $today = db_select('node_stat', 'd')
      ->fields('d')
      ->condition('nid', $node->nid)
      ->condition('last_viewed', REQUEST_TIME - 86400, '>=')
      ->execute();
    $num_today = $today->rowCount();

    $user_saved = db_select('node_stat', 'd')
      ->fields('d',array('uid'))
      ->condition('nid', $node->nid)
      ->condition('last_viewed', REQUEST_TIME - 86400, '>=')
      ->execute();

    $user_fields = user_load($record->uid);
    $t_args = array(
      '%uid' => $record->uid,
      '%date' => date('H - i j M, Y', $record->last_viewed),
      '%user' => $user_fields ->name,
      '%times_total' => $num_of_total,
      '%times_today' => $num_today,
    );

    $node->content['node_views'] = array(
      '#markup' => t('This page has been viewed %times_total total.Today only %times_today.  It was last viewed by %user on %date.', $t_args),
      '#weight' => 10,
    );
  }
}

function node_stat_get_record($nid,$uid) {
  $query = db_select('node_stat', 'd')
    ->fields('d', array('nid', 'uid', 'last_viewed'))
    ->condition('nid', $nid)
    ->condition('uid', $uid);
  $record = $query->execute()->fetch();
  return $record;
}


function node_stat_set_record($record) {
  if (!is_object($record)) {
    return watchdog('node_stat', 'We could not update information about node views.', array(), WATCHDOG_ERROR);
  } else{
  if ($record->uid == 0) {
    return watchdog('node_stat', 'We do not count anonymous users.', array(), WATCHDOG_ERROR);
  }
  }
  $query = db_insert('node_stat')
    ->fields((array) $record);
  $query->execute();

}







